// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// compute_log_constant
NumericVector compute_log_constant(NumericVector log_lambda, NumericVector nu, int maxiter);
RcppExport SEXP _mpcmp_compute_log_constant(SEXP log_lambdaSEXP, SEXP nuSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type log_lambda(log_lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_log_constant(log_lambda, nu, maxiter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mpcmp_compute_log_constant", (DL_FUNC) &_mpcmp_compute_log_constant, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_mpcmp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
