# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
logZ_c <- function(log_lambda, nu, summax) {
    .Call(`_mpcmp_logZ_c`, log_lambda, nu, summax)
}

